name: YouTube Live Recorder

on:
  workflow_dispatch:   # دستی اجرا (میتونی بعدا schedule هم بذاری)

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yt-dlp google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Download YouTube live (wait until live starts)
        run: |
          yt-dlp -o "live_record.%(ext)s" --wait-for-video "https://www.youtube.com/@ForTNiteclips.2/live"

      - name: Upload to Google Drive
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_JSON }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: |
          echo "$CLIENT_SECRET" > client_secret.json
          echo "$TOKEN_JSON" > token.json
          python upload_to_drive.py
